typedef struct no *Lista;
Lista cria_lista();
int lista_vazia(Lista lst);
int insere_ord(Lista *lst, int elem);
int remove_ord(Lista *lst, int elem);
Lista imprime_lista(Lista *lst);
int menor_elem(Lista *lst);
int tamanho(Lista *lst);
int remove_impares(Lista *lst);
int iguais(Lista *lst1, Lista *lst2);
Lista intercala(Lista *lst1, Lista *lst2);
